export { createTMDB, TMDBClient, type TMDBFactoryOptions } from './client'
export { TMDBError, TMDBRequestError, TMDBResponseError } from './errors'
export { buildImageUrl } from './query'
export {
  isMovie,
  isMovieSearchResult,
  isPerson,
  isPersonSearchResult,
  isTV,
  isTVSearchResult,
} from './search-guards'
export type { ImageUrlTransform } from './resources/images'

export type {
  FetchLike,
  TMDBAccessTokenAuth,
  TMDBApiKeyAuth,
  TMDBAuth,
  TMDBClientOptions,
  TMDBImagesOptions,
  TMDBRequestOptions,
  TMDBTransport,
} from './http'

export type {
  BackdropSize,
  CollectionSummary,
  Configuration,
  ConfigurationImages,
  Country,
  CreditCastMember,
  CreditCrewMember,
  CreditsResponse,
  Genre,
  GenresResponse,
  ImageItem,
  ImageQueryOptions,
  ImagesResponse,
  ImageSize,
  JobDepartment,
  Language,
  LanguageCode,
  LanguageOptions,
  ListOptions,
  LogoSize,
  MediaType,
  MovieAppendToResponse,
  MovieDetails,
  MovieDetailsOptions,
  MovieSearchOptions,
  MovieSearchResult,
  MovieMultiResult,
  MovieSummary,
  MultiSearchOptions,
  Network,
  PagedResponse,
  PersonDetails,
  PersonKnownFor,
  PersonKnownForMovie,
  PersonKnownForTV,
  PersonMultiResult,
  PersonSearchResult,
  PersonSummary,
  PosterSize,
  ProductionCompany,
  ProductionCountry,
  ProfileSize,
  RegionCode,
  SearchMultiResult,
  TVMultiResult,
  EpisodeGuestStar,
  EpisodeSummary,
  SeasonSummary,
  SpokenLanguage,
  StillSize,
  Timezone,
  TMDBDateString,
  TMDBObject,
  TrendingResult,
  TrendingTimeWindow,
  TVAppendToResponse,
  TVDetails,
  TVDetailsOptions,
  TVSeasonAppendToResponse,
  TVSeasonDetails,
  TVSeasonDetailsOptions,
  TVSearchOptions,
  TVSearchResult,
  TVSummary,
  Video,
  VideosResponse,
} from './types'
